services:
  # Backend API Service
  - type: web
    name: meal-planner-api
    env: go
    plan: free
    buildCommand: cd backend && go build -o main cmd/server/main.go
    startCommand: cd backend && ./main
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: PORT
        fromService:
          type: web
          name: meal-planner-api
          property: port
      - key: MONGODB_URI
        sync: false  # Set this manually in Render dashboard
      - key: JWT_SECRET
        sync: false  # Set this manually in Render dashboard
    
  # Frontend Static Site Service  
  - type: static
    name: meal-planner-frontend
    env: static
    plan: free
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_API_URL
        fromService:
          type: web
          name: meal-planner-api
          property: host
        value: https://meal-planner-api.onrender.com/api
